version: '3.8'

services:
  mydoc-client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    container_name: mydoc-client
    restart: always
    ports:
      - "3033:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    # Tambahkan batasan resource jika hardware Anda terbatas
    deploy:
      resources:
        limits:
          cpus: '2.0'       # Batasi maksimal menggunakan 2 Cores CPU
          memory: 1024M     # Batasi maksimal 1 GB RAM (NextJS standalone sangat aman di < 1GB)